
package View;

import Config.Koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class menuKategori extends javax.swing.JPanel {


    private final Connection conn;

    public menuKategori() {
        initComponents();

        conn = Koneksi.getConnection();
        setTabelModel();
        loadData();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/peopleIconKecil.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Data Kategori Perpustakaan");

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");

        jTextField1.setText("Cari");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Master Data > Kategori ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18))
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        showPanel();
        loadData();
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        showPanel();
        loadData();
    }

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtDeskripsi_KategoriActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtTeleponActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        panelMain.removeAll();
        panelMain.add(panelAdd);
        panelMain.repaint();
        panelMain.revalidate();

        txtID.setText(setIDKategori());
        if(btnAdd.getText().equals(UBAH)){
            dataTabel();
            btnSave.setText("PERBARUI")
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        if(btnSave.getText().equals("TAMBAH"))
        {
            btnSave.setText("SIMPAN");
        }
        else if(btnSave.getText().equals("SIMPAN"))
        {
            insertData();
        }
        else if (btnSave.getText().equals("PERBARUI"))
        {
            updateData();
        }
    }
private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {
        if(btnAdd.getText().equals("TAMBAH")); {
            btnAdd.setText("UBAH");
            btnDelete.setVisible(true);
            btnCancel.setVisible(true);
    }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        deleteData();
    }

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {
        searchData();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

private void loadData() {
        getData((DefaultTableModel) tblData.getModel());
        btnDelete.setVisible(false);
        btnCancel.setVisible(false);
    }

    private void showPanel() {
        panelMain.removeAll();
        panelMain.add(new MenuKategori());
        panelMain.repaint();
        panelMain.revalidate();
    }

    private void resetForm() {
        txtID.setText("");
        txtNama.setText("");
        txtDeskripsi_Kategori.setText("");
        txtTelepon.setText("");
        rbJenisKelamin.clearSelection();
        txtTanggal.setText("");
    }


    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Deskripsi_Kategori");
        model.addColumn("Telepon");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tanggal Bergabung");
    }
private void getData(DefaultTableModel model) {
        model.setRowCount(0);

        try { 
            String sql = "SELECT * FROM Kategori";
        try (PreparedStatement st = conn.prepareStatement(sql)){
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                String idKategori        = rs.getString("ID_Kategori");
                String namaKategori      = rs.getString("Nama_Kategori");
                String deskripsiKategori     = rs.getString("Deskripsi_Kategori");
                String teleponKategori   = rs.getString("Telepon");
                String jenisKelamin     = rs.getString("Jenis_kelamin");
                String tanggalBergabung = rs.getString("Tanggal_Bergabung");

                Object[] rowData = {idKategori,namaKategori,deskripsiKategori,teleponKategori,jenisKelamin,tangalBergabung};
                model.addRow(rowData);
            }
            String sql = "SELECT * FROM Kategori";
        } catch (Exception e) {
            Logger.getLogger(MenuKategori.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    }
private String setIDKategori (){
        String urutan  = null ;
        Date now = new Date();
        SimpleDateFormat noFormat = new simpleDateFormat("yyMM");
        String no = noFormat.format(now);

        String sql = "SELECT RIGHT(ID_Kategori, 3) AS Nomor " +
                     "FROM Kategori " +
                     "WHERE ID_Kategori LIKE 'AGT" + no + "%'" +
                     "ORDER BY ID_Kategori DESC " +
                     "LIMIT 1";

        try (PreparedStatement st = conn.prepareStatement(sql)){
            ResultSet rs = st.executeQuery();

            if (rs.next()){
                int nomor = Integer.parseInt(rs.getString("Nomor" + 1));
                urutan = "AGT" + no + String.format("%3d", nomor);
            }else{
                urutan = "AGT" + no + "001";
            }

        } catch (Exception e) {
            java.util.logging.Logger.getLogger(MenuKategori.class.getName()).log(Level.SEVERE,null,e);
        }

        return urutan;

    }
private void insertData() {
        String idKategori = txtID.getText();
        String namaKategori = txtNama.getText();
        String deskripsiKategori = txtDeskripsi_Kategori.getText();
        String teleponKategori = txtTelepon.getText();
        String jenisKelamin;
            if (rbLaki.isSelected()){
                jenisKelamin = rbLaki.getText();
            } else if(rbPerempuan.isSelected()){
                jenisKelamin = rbPeremmpuan.getText();
            } else {
                jenisKelamin = "";
            }

        String tanggalBergabung = txtTanggal.getText();

        if(idKategori.isEmpty()  idKategori.isEmpty() 
 idKategori.isEmpty()  idKategori.isEmpty() 
 idKategori.isEmpty()  idKategori.isEmpty() 
 ){
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "INSERT INTO Kategori (ID_Kategori,Nama_Kategori, Deskripsi_Kategori, Telepon, Jenis_Kelamin, Tanggal_Bergabung) VALUES(?,?,?,?,?,?)";
            try (PreparedStatement st = conn prepareStatement(sql)){
                st.setString(1,idKategori);
                st.setString(2,namaKategori);
                st.setString(3,deskripsiKategori);
                st.setString(4,teleponKategori);
                st.setString(5,jenisKelamin);
                st.setString(6,tanggalBergabung);

                int rowInserted = st.executeUpdate();
                if(rowInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(MenuKategori.class.getName()).log(Level.SEVERE,null,e);
        }
    }
private void dataTabel() {
        panelView.setVisible(false);
        panelAdd.setVisible(true);

        int row = tblData.getSelectedRow();
        jLabel6.setText("Perbarui Data Kategori Perpustakaan");

        txtID.setEnabled(false);
        txtTanggal.setEnabled(false);

        txtID.setText(tblData.getValueAt(row,0).toString());
        txtNama.setText(tblData.getValueAt(row,1).toString());
        txtDeskripsi_Kategori.setText(tblData.getValueAt(row,2).toString());
        txtTelepon.setText(tblData.getValueAt(row,3).toString());

        String jenisKelamin = tblData.getValueAt(row,4)toString();
            if(jenisKelamin.equals("Laki-laki")){
                rblaki.setSelected(true);
            } else if(jenisKelamin.equals("Perempuan")) {
                rbPerempuan.setSelected(true);
            }


         txtTanggal(tblData.getValueAt(row, 5).toString()); 
    }
private void updateData() {
        String idKategori = txtID.getText();
        String namaKategori = txtNama.getText();
        String deskripsiKategori = txtDeskripsi_Kategori.getText();
        String teleponKategori = txtTelepon.getText();
        String jenisKelamin;
            if (rbLaki.isSelected()){
                jenisKelamin = rbLaki.getText();
            } else if(rbPerempuan.isSelected()){
                jenisKelamin = rbPeremmpuan.getText();
            } else {
                jenisKelamin = "";
            }

        String tanggalBergabung = txtTanggal.getText();

        if(idKategori.isEmpty()  idKategori.isEmpty() 
 idKategori.isEmpty()  idKategori.isEmpty() 
 idKategori.isEmpty()  idKategori.isEmpty() 
 ){
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
try {
            String sql = "UPDATE Kategori SET Nama_Kategori=?, Deskripsi_Kategori=?,WHERE ID_Kategori=?";
            try (PreparedStatement st = conn prepareStatement(sql)){
                st.setString(1,namaKategori);
                st.setString(2,deskripsiKategori);
                st.setString(3,idKategori);

                int rowUpadated = st.executeUpdate();
                if(rowUpadate> 0) {
                    JOptionPane.showMessageDialog(this, "Data BerhasilData Diperabua
                    loadData();
                    showPanel();
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(MenuKategori.class.getName()).log(Level.SEVERE,null,e);
        }
    }


}
private void deleteData() {
        int selectedRow = tblData.getSelectedRow)();
        int confirm = JOption.showConfirmDialog(this, "Apakah yakin ingin mengahpus data ini ?",
                "Konfirmasi Hapus",
                JOptionPane.YEX_NO_OPTION);

        if(confirm == JOptionPane.YES_OPTION) {
            String id = tblData.getValueAt(selectedRow, 0).toString();
            try {
                String sql = "DELETE FROM Kategori WHERE ID_Kategori=?";
                try(PreparedStatement st = conn.prepareStatement(sql)) {
                    st.setString(1, id);

                    int rowDeleted = st.executeUpdate();
                    if(rowDeleted > 0) {
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    }else{
                        JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
                    }
                }
        } catch (Exception e) {
            Logger.getLogger(MenuKategori.class.getName()).log(Level.SEVERE, null, e);
        }
        }
        resetForm();
            loadData();
            showPanel();
    }
private void searchData() {
        String kataKunci = txtSearch.getText();

        DefaultTableModel model = (DefaultTableModel) tblData.getModel(); 
        model.setRowCount(0);

        try {
            String sql = "SELECT * FROM Kategori WHERE NAMA_Kategori LIKE ?, Deskripsi_Kategori LIKE ?";
            st.setString(1, "%" + kataKunci + "%");
            st.setString(2, "%" + kataKunci + "%");
        try (PreparedStatement st = conn.prepareStatement(sql)){
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                String idKategori        = rs.getString("ID_Kategori");
                String namaKategori      = rs.getString("Nama_Kategori");
                String deskripsiKategori     = rs.getString("Deskripsi_Kategori");
               

                Object[] rowData = {idKategori,namaKategori,deskripsiKategori};
                model.addRow(rowData);
            }
            String sql = "SELECT * FROM Kategori";
        } catch (SQLException e) {
            Logger.getLogger(MenuKategori.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    }   



