/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Menu.menuKategori;
import javax.swing.table.DefaultTableModel;
import Koneksi.koneksi; // Sesuaikan dengan package koneksi Anda
import Tampilan.MenuUtama;
import java.sql.Connection;
import java.sql.PreparedStatement; // INI YANG TADI KURANG
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafli
 */
public class menuCRUDKategori extends javax.swing.JPanel {

    /**
     * Creates new form menuAnggota
     */
    public menuCRUDKategori() {
        initComponents();
        btnSimpan.setVisible(false); // Sembunyikan Simpan, tampilkan Tambah
        btnTambah.setVisible(true);
        generateIdKategori();
       
    }
    
    private void generateIdKategori() {
    // Mengambil ID Kategori terakhir dari tabel kategori_buku
        String sql = "SELECT ID_Kategori FROM kategori_buku ORDER BY ID_Kategori DESC LIMIT 1";

        try {
            java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Ambil ID Kategori terakhir (misal: "KTG001")
                String lastId = rs.getString("ID_Kategori");

                // Potong string "KTG" dan ambil angkanya ("001" -> 1)
                int idNum = Integer.parseInt(lastId.substring(3));

                // Tambah 1 untuk ID baru
                idNum++;

                // Format kembali menjadi 3 digit (misal: 2 -> "KTG002")
                String newId = String.format("KTG%03d", idNum);
                tfIdKategori.setText(newId);
            } else {
                // Jika database masih kosong, mulai dari KTG001
                tfIdKategori.setText("KTG001");
            }

            // Kunci field ID agar tidak bisa diubah manual oleh user
            tfIdKategori.setEditable(false);

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal generate ID: " + e.getMessage());
        }
    }
    
    public menuCRUDKategori(String id, String nama, String deskripsi) {
    initComponents();
    tfIdKategori.setText(id);      // Sesuaikan dengan nama variabel TextField Anda
    tfNamaKategori.setText(nama);
    tfDeskripsi.setText(deskripsi);
    btnTambah.setVisible(false); // Sembunyikan Tambah, tampilkan Simpan
    btnSimpan.setVisible(true);
    
    // Opsional: set ID agar tidak bisa diedit saat mode edit
    tfIdKategori.setEditable(false);
}
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfIdKategori = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNamaKategori = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDeskripsi = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/KategoriMini.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tambah Kategori Buku");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Master Data > Kategori > Tambah Kategori");

        jLabel3.setText("ID");

        jLabel4.setText("Nama");

        jLabel5.setText("Deskripsi");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addComponent(tfIdKategori)
                            .addComponent(tfNamaKategori)
                            .addComponent(tfDeskripsi)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addComponent(tfDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(483, 483, 483))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
    MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (menuUtama != null) {
            menuUtama.showPanel(new menuKategori());
        } 
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    String id = tfIdKategori.getText().trim();
    String nama = tfNamaKategori.getText().trim();
    String deskripsi = tfDeskripsi.getText().trim();

    // Validasi Input Kosong
    if (id.isEmpty() || nama.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID dan Nama Kategori wajib diisi!");
        return;
    }

    try {
        java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
        
        // Cek ID sudah ada di database
        String sqlCek = "SELECT COUNT(*) FROM kategori_buku WHERE ID_Kategori = ?";
        java.sql.PreparedStatement stCek = conn.prepareStatement(sqlCek);
        stCek.setString(1, id);
        java.sql.ResultSet rs = stCek.executeQuery();
        
        if (rs.next() && rs.getInt(1) > 0) {
            // Jika ID sudah ada, tampilkan peringatan
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal: ID Kategori '" + id + "' sudah terdaftar!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Jika ID belum ada, lakukan INSERT data baru
        String sqlInsert = "INSERT INTO kategori_buku (ID_Kategori, Nama_Kategori, Deskripsi) VALUES (?, ?, ?)";
        java.sql.PreparedStatement stInsert = conn.prepareStatement(sqlInsert);
        stInsert.setString(1, id);
        stInsert.setString(2, nama);
        stInsert.setString(3, deskripsi);
        stInsert.executeUpdate();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Data kategori berhasil ditambahkan!");
        
        // Clean kolom input ketika sukses
        tfIdKategori.setText("");
        tfNamaKategori.setText("");
        tfDeskripsi.setText("");
        tfIdKategori.requestFocus();
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error Database: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    String id = tfIdKategori.getText().trim();
    String nama = tfNamaKategori.getText().trim();
    String deskripsi = tfDeskripsi.getText().trim();

    // Validasi Input Kosong
    if (id.isEmpty() || nama.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID dan Nama Kategori wajib diisi!");
        return;
    }

    try {
        java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
        
        // Cek apakah ID sudah ada
        String sqlCek = "SELECT COUNT(*) FROM kategori_buku WHERE ID_Kategori = ?";
        java.sql.PreparedStatement stCek = conn.prepareStatement(sqlCek);
        stCek.setString(1, id);
        java.sql.ResultSet rs = stCek.executeQuery();
        
        if (rs.next() && rs.getInt(1) > 0) {
            if (!tfIdKategori.isEditable()) {
                String sqlUpdate = "UPDATE kategori_buku SET Nama_Kategori = ?, Deskripsi = ? WHERE ID_Kategori = ?";
                java.sql.PreparedStatement stUpdate = conn.prepareStatement(sqlUpdate);
                stUpdate.setString(1, nama);
                stUpdate.setString(2, deskripsi);
                stUpdate.setString(3, id);
                stUpdate.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal: ID Kategori '" + id + "' sudah terdaftar!");
                return; 
            }
        } else {
            String sqlInsert = "INSERT INTO kategori_buku (ID_Kategori, Nama_Kategori, Deskripsi) VALUES (?, ?, ?)";
            java.sql.PreparedStatement stInsert = conn.prepareStatement(sqlInsert);
            stInsert.setString(1, id);
            stInsert.setString(2, nama);
            stInsert.setString(3, deskripsi);
            stInsert.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        }
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error Database: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField tfDeskripsi;
    private javax.swing.JTextField tfIdKategori;
    private javax.swing.JTextField tfNamaKategori;
    // End of variables declaration//GEN-END:variables
}
