/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Menu.menuPenerbit;
import javax.swing.table.DefaultTableModel;
import Koneksi.koneksi; // Sesuaikan dengan package koneksi Anda
import Tampilan.MenuUtama;
import java.sql.Connection;
import java.sql.PreparedStatement; // INI YANG TADI KURANG
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafli
 */
public class menuCRUDPenerbit extends javax.swing.JPanel {

    /**
     * Creates new form menuAnggota
     */
    public menuCRUDPenerbit() {
        initComponents();
        btnSimpan.setVisible(false); // Sembunyikan Simpan, tampilkan Tambah
        btnTambah.setVisible(true);
       
    }
    
    public menuCRUDPenerbit(String id, String nama, String situs) {
    initComponents();
    btnTambah.setVisible(false); // Sembunyikan Tambah, tampilkan Simpan
    btnSimpan.setVisible(true);
    tfIdPenerbit.setText(id);
    tfNamaPenerbit.setText(nama);
    tfSitusPenerbit.setText(situs);
    tfIdPenerbit.setEditable(false);
    
}
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfIdPenerbit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNamaPenerbit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfSitusPenerbit = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/peopleIconKecil.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tambah Data Penerbit Buku ");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Master Data > Penerbit > Tambah Penerbit");

        jLabel3.setText("ID");

        jLabel4.setText("Nama");

        jLabel5.setText("Situs");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 1393, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfSitusPenerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1382, Short.MAX_VALUE)
                            .addComponent(tfNamaPenerbit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdPenerbit, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfIdPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNamaPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSitusPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(497, 497, 497))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (menuUtama != null) {
            menuUtama.showPanel(new menuPenerbit());
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    String id = tfIdPenerbit.getText().trim();
    String nama = tfNamaPenerbit.getText().trim();
    String situs = tfSitusPenerbit.getText().trim();

    // 2. Validasi input
    if (id.isEmpty() || nama.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID dan Nama Penerbit tidak boleh kosong!");
        return;
    }

    // 3. Proses simpan ke database
    try {
        java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
        String sql = "INSERT INTO penerbit (id_penerbit, nama_penerbit, situs) VALUES (?, ?, ?)";
        java.sql.PreparedStatement st = conn.prepareStatement(sql);
        
        st.setString(1, id);
        st.setString(2, nama);
        st.setString(3, situs);
        
        int rowsInserted = st.executeUpdate();
        
        if (rowsInserted > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            // Opsional: Kosongkan field setelah berhasil
            tfIdPenerbit.setText("");
            tfNamaPenerbit.setText("");
            tfSitusPenerbit.setText("");
        }
        
    } catch (java.sql.SQLException e) {
        if (e.getErrorCode() == 1062) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal: ID Penerbit '" + id + "' sudah ada di database.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    String id = tfIdPenerbit.getText().trim();
    String nama = tfNamaPenerbit.getText().trim();
    String situs = tfSitusPenerbit.getText().trim();

    // 1. Validasi Input
    if (id.isEmpty() || nama.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID dan Nama Penerbit wajib diisi!");
        return;
    }

    try {
        java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
        
        // 2. Cek apakah ini mode Edit (jika ID tidak bisa diedit) atau Tambah baru
        if (!tfIdPenerbit.isEditable()) {
            // LOGIKA UPDATE
            String sql = "UPDATE penerbit SET nama_penerbit = ?, situs = ? WHERE id_penerbit = ?";
            java.sql.PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, nama);
            st.setString(2, situs);
            st.setString(3, id);
            st.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
        } else {
            // LOGIKA TAMBAH (INSERT)
            // Validasi duplikasi ID untuk data baru
            String sqlCek = "SELECT COUNT(*) FROM penerbit WHERE id_penerbit = ?";
            java.sql.PreparedStatement stCek = conn.prepareStatement(sqlCek);
            stCek.setString(1, id);
            java.sql.ResultSet rs = stCek.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal: ID Penerbit '" + id + "' sudah ada!");
                return;
            }
            
            String sql = "INSERT INTO penerbit (id_penerbit, nama_penerbit, situs) VALUES (?, ?, ?)";
            java.sql.PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, id);
            st.setString(2, nama);
            st.setString(3, situs);
            st.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        }
        
        // Tutup form atau kembali ke panel utama
        // Anda bisa memanggil method untuk kembali ke panel tabel di sini
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error Database: " + e.getMessage());
    }            // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfIdPenerbit;
    private javax.swing.JTextField tfNamaPenerbit;
    private javax.swing.JTextField tfSitusPenerbit;
    // End of variables declaration//GEN-END:variables
}
