/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Menu.menuPetugas;
import javax.swing.table.DefaultTableModel;
import Koneksi.koneksi; // Sesuaikan dengan package koneksi Anda
import Tampilan.MenuUtama;
import java.sql.Connection;
import java.sql.PreparedStatement; // INI YANG TADI KURANG
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafli
 */
public class menuCRUDPetugas extends javax.swing.JPanel {

    /**
     * Creates new form menuAnggota
     */
    public menuCRUDPetugas() {
        initComponents();
        btnSimpan.setVisible(false); // Sembunyikan Simpan, tampilkan Tambah
        btnTambah.setVisible(true);
        autoGenerateID();
    }
    
    private void autoGenerateID() {
        try {
            java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
            // Mengambil ID_Admin terbesar/terakhir
            String sql = "SELECT ID_Admin FROM data_admin ORDER BY ID_Admin DESC LIMIT 1";
            java.sql.PreparedStatement st = conn.prepareStatement(sql);
            java.sql.ResultSet rs = st.executeQuery();

            if (rs.next()) {
                String lastID = rs.getString("ID_Admin"); // Contoh hasil: "ADM003"
                // Mengambil angka dari substring setelah "ADM" (indeks ke-3 sampai selesai)
                int idNum = Integer.parseInt(lastID.substring(3)) + 1; 

                // Format kembali angka menjadi 3 digit (contoh: 4 -> "ADM004")
                String newID = String.format("ADM%03d", idNum);
                tfIdPetugas.setText(newID);
            } else {
                // Jika database masih kosong, mulai dari ADM001
                tfIdPetugas.setText("ADM001");
            }

            // Buat agar textfield ID tidak bisa diedit manual oleh user
            tfIdPetugas.setEditable(false); 

        } catch (Exception e) {
            System.out.println("Error saat generate ID: " + e.getMessage());
        }
    }
    
    
    public menuCRUDPetugas(String idPetugas, String nama, String username, String email, String password) {
        initComponents(); // Tetap panggil ini untuk inisialisasi komponen GUI
        btnTambah.setVisible(false); // Sembunyikan Tambah, tampilkan Simpan
        btnSimpan.setVisible(true);
        
        
        tfIdPetugas.setText(idPetugas);
        tfNamaPetugas.setText(nama);
        tfUsernamePetugas.setText(username);
        tfEmailPetugas.setText(email);
        pfPasswordPetugas.setText(password);
        
        // Jika level adalah ComboBox:
        
        // Opsional: Kunci ID jika tidak boleh diubah saat edit
        tfIdPetugas.setEditable(false); 
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfIdPetugas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNamaPetugas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfUsernamePetugas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfEmailPetugas = new javax.swing.JTextField();
        pfPasswordPetugas = new javax.swing.JPasswordField();
        btnSimpan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/LogoPetugasMini.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Data Petugas Perpustakaan");

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Master Data > Petugas > Tambah Petugas");

        jLabel3.setText("ID");

        jLabel4.setText("Nama");

        jLabel5.setText("Username");

        jLabel6.setText("Email");

        jLabel7.setText("Password");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pfPasswordPetugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1392, Short.MAX_VALUE)
                            .addComponent(tfEmailPetugas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUsernamePetugas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNamaPetugas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdPetugas, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 1368, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIdPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNamaPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addComponent(tfUsernamePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmailPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPasswordPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
         MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (menuUtama != null) {
            menuUtama.showPanel(new menuPetugas());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String id = tfIdPetugas.getText().trim();
        String nama = tfNamaPetugas.getText().trim();
        String username = tfUsernamePetugas.getText().trim();
        String email = tfEmailPetugas.getText().trim();
        String password = new String(pfPasswordPetugas.getPassword()); // Mengambil password

        // 1. Validasi Input
        if (id.isEmpty() || nama.isEmpty() || username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua data wajib diisi dengan benar!");
            return;
        }

        try {
            java.sql.Connection conn = Koneksi.koneksi.getKoneksi();

            // 2. Cek apakah ini mode Edit (ID tidak bisa diedit)
            if (!tfIdPetugas.isEditable()) {
                // LOGIKA UPDATE
                // Jika password dikosongkan, kita bisa memilih untuk tidak mengubah password
                String sql = "UPDATE data_admin SET Nama = ?, Username = ?, Email = ?, Password = ? WHERE ID_Admin = ?";
                java.sql.PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, nama);
                st.setString(2, username);
                st.setString(3, email);
                st.setString(4, password);
                st.setString(5, id);

                st.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            } else {
                // LOGIKA TAMBAH (INSERT)
                String sqlCek = "SELECT COUNT(*) FROM data_admin WHERE ID_Admin = ?";
                java.sql.PreparedStatement stCek = conn.prepareStatement(sqlCek);
                stCek.setString(1, id);
                java.sql.ResultSet rs = stCek.executeQuery();

                if (rs.next() && rs.getInt(1) > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal: ID Petugas '" + id + "' sudah terdaftar!");
                    return;
                }

                String sql = "INSERT INTO data_admin (ID_Admin, Nama, Username, Email, Password) VALUES (?, ?, ?, ?, ?)";
                java.sql.PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, id);
                st.setString(2, nama);
                st.setString(3, username);
                st.setString(4, email);
                st.setString(5, password);

                st.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            }

            // Kembali ke menu tabel petugas
            btnBatalActionPerformed(evt);

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Database: " + e.getMessage());
        }            // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        

    String id = tfIdPetugas.getText().trim();
    String nama = tfNamaPetugas.getText().trim();
    String username = tfUsernamePetugas.getText().trim();
    String email = tfEmailPetugas.getText().trim();
    String password = new String(pfPasswordPetugas.getPassword()).trim();

    // ================== VALIDASI ==================
    if (id.isEmpty() || nama.isEmpty() || username.isEmpty()
            || email.isEmpty() || password.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Semua kolom data wajib diisi, tidak boleh kosong!",
                "Validasi Gagal",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Query SQL
    String sql = "INSERT INTO data_admin (ID_Admin, Nama, Username, Email, Password) VALUES (?, ?, ?, ?, ?)";

    try {
        // Koneksi database
        java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
        java.sql.PreparedStatement st = conn.prepareStatement(sql);

        // Isi parameter
        st.setString(1, id);
        st.setString(2, nama);
        st.setString(3, username);
        st.setString(4, email);
        st.setString(5, password);

        // Eksekusi
        st.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

        // Kembali ke menu Petugas
        MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (menuUtama != null) {
            menuUtama.showPanel(new menuPetugas());
        }

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal menyimpan data!\n" + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnTambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pfPasswordPetugas;
    private javax.swing.JTextField tfEmailPetugas;
    private javax.swing.JTextField tfIdPetugas;
    private javax.swing.JTextField tfNamaPetugas;
    private javax.swing.JTextField tfUsernamePetugas;
    // End of variables declaration//GEN-END:variables
}
