/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.table.DefaultTableModel;
import Koneksi.koneksi; // Sesuaikan dengan package koneksi Anda
import java.sql.Connection;
import java.sql.PreparedStatement; // INI YANG TADI KURANG
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import Tampilan.MenuUtama;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Component;
import java.awt.Image;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
/**
 *
 * @author rafli
 */
public class menuBuku extends javax.swing.JPanel {

    /**
     * Creates new form menuAnggota
     */
    public menuBuku() {
        initComponents();
        
        btnUbah.setVisible(false);
        btnHapus.setVisible(false);
        btnBatal.setVisible(false);
        setTabelModel();
        loadData();
    }
    
    private void setTabelModel() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                // Beritahu tabel bahwa kolom 10 berisi Icon/Gambar
                if (columnIndex == 10) return javax.swing.ImageIcon.class;
                return super.getColumnClass(columnIndex);
            }
        };

        model.addColumn("No");
        model.addColumn("ID Buku");
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Tahun Terbit");
        model.addColumn("ID Kategori");
        model.addColumn("Kategori");
        model.addColumn("ID Penerbit");
        model.addColumn("Penerbit");
        model.addColumn("Stok");
        model.addColumn("Cover"); // Kolom index 10
        model.addColumn("Jumlah Halaman");

        jTable1.setModel(model);

        // Terapkan renderer ke kolom Cover (index 10)
        jTable1.getColumnModel().getColumn(10).setCellRenderer(new ImageRenderer());
    }
    
    public void loadData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    try {
        Connection conn = Koneksi.koneksi.getKoneksi();
        // Query mengambil data dari tabel utama dan tabel relasi
        String sql = "SELECT b.id_buku, b.judul_buku, b.pengarang, b.tahun_terbit, " +
             "b.id_kategori, k.nama_kategori, b.id_penerbit, p.nama_penerbit, " +
             "b.stok, b.cover, b.jumlah_halaman " +
             "FROM buku b " +
             "JOIN kategori_buku k ON b.id_kategori = k.id_kategori " +
             "JOIN penerbit p ON b.id_penerbit = p.id_penerbit " +
             "ORDER BY b.id_buku ASC";

        java.sql.Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        int no = 1;
        while (rs.next()) {
        model.addRow(new Object[]{
            no++,
            rs.getString("id_buku"),
            rs.getString("judul_buku"), // Perubahan di sini
            rs.getString("pengarang"),
            rs.getString("tahun_terbit"),
            rs.getString("id_kategori"),
            rs.getString("nama_kategori"),
            rs.getString("id_penerbit"),
            rs.getString("nama_penerbit"),
            rs.getString("stok"),
            rs.getString("cover"),
            rs.getString("jumlah_halaman")
        });
    }
    } catch (Exception e) {
        System.out.println("Error loadData: " + e.getMessage());
    }
    }
    
   
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        tfCari = new palette.Custom_JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(50);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/peopleIconKecil.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Data Kategori Buku Perpustakaan");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Master Data > Kategori ");

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel13)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
            btnUbah.setVisible(false);
            btnHapus.setVisible(false);
            btnBatal.setVisible(false);
            btnTambah.setVisible(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
                                        
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
     MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (menuUtama != null) {
            menuUtama.showPanel(new menuCRUDBuku());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int baris = jTable1.getSelectedRow();
        if (baris != -1) {
            // AMBIL DATA - Pastikan index (1, 2, dst) sesuai urutan kolom di JTable Anda!
            String idBuku      = jTable1.getValueAt(baris, 1).toString();
            String judul       = jTable1.getValueAt(baris, 2).toString();
            String pengarang   = jTable1.getValueAt(baris, 3).toString();
            String tahun       = jTable1.getValueAt(baris, 4).toString();
            String idKategori  = jTable1.getValueAt(baris, 5).toString();
            String idPenerbit  = jTable1.getValueAt(baris, 7).toString();
            String stok        = jTable1.getValueAt(baris, 9).toString();
            String cover       = jTable1.getValueAt(baris, 10).toString(); // Pastikan index kolom gambar benar
            String jmlHalaman  = jTable1.getValueAt(baris, 11).toString();

            // DEBUG: Cek di Output NetBeans apakah path cover terambil
            System.out.println("Path Gambar yang dikirim: " + cover);

            MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
            if (menuUtama != null) {
                menuUtama.showPanel(new menuCRUDBuku(idBuku, judul, pengarang, tahun, idKategori, idPenerbit, jmlHalaman, stok, cover));
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel terlebih dahulu!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        String idBuku = jTable1.getValueAt(selectedRow, 1).toString();
        Connection conn = Koneksi.koneksi.getKoneksi();
        
        // 1. Ambil path gambar dari database sebelum dihapus
        String pathGambar = "";
        String sqlGet = "SELECT cover FROM buku WHERE Id_Buku = ?";
        PreparedStatement psGet = conn.prepareStatement(sqlGet);
        psGet.setString(1, idBuku);
        ResultSet rs = psGet.executeQuery();
        if (rs.next()) {
            pathGambar = rs.getString("cover");
        }

        // 2. Eksekusi Hapus dari Database
        String sqlDelete = "DELETE FROM buku WHERE Id_Buku = ?";
        PreparedStatement psDelete = conn.prepareStatement(sqlDelete);
        psDelete.setString(1, idBuku);
        psDelete.executeUpdate();

        // 3. Hapus file fisik dari folder 'uploads'
        if (pathGambar != null && !pathGambar.isEmpty()) {
            // Path relatif diubah jadi absolut untuk menghapus file
            Path fileToDelete = Paths.get(System.getProperty("user.dir"), pathGambar);
            Files.deleteIfExists(fileToDelete);
        }

        // 4. Hapus baris dari Tabel
        ((DefaultTableModel) jTable1.getModel()).removeRow(selectedRow);

        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            btnUbah.setVisible(true);
            btnHapus.setVisible(true);
            btnBatal.setVisible(true);
            btnTambah.setVisible(false);       
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private palette.Custom_JTextField tfCari;
    // End of variables declaration//GEN-END:variables
}

class ImageRenderer extends DefaultTableCellRenderer {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, 
            boolean isSelected, boolean hasFocus, int row, int column) {
        
        JLabel label = new JLabel();
        if (value != null && !value.toString().isEmpty()) {
            // Mengambil path relatif (misal: uploads/buku1.jpg)
            String path = System.getProperty("user.dir") + "/" + value.toString();
            ImageIcon icon = new ImageIcon(path);
            
            // Resize gambar agar pas di dalam baris tabel
            Image img = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(img));
            label.setHorizontalAlignment(JLabel.CENTER);
        }
        return label;
    }
}
