/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.table.DefaultTableModel;
import Koneksi.koneksi; // Sesuaikan dengan package koneksi Anda
import java.sql.Connection;
import java.sql.PreparedStatement; // INI YANG TADI KURANG
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import Tampilan.MenuUtama;

/**
 *
 * @author rafli
 */
public class menuBuku extends javax.swing.JPanel {

    /**
     * Creates new form menuAnggota
     */
    public menuBuku() {
        initComponents();
        setTabelModel();
        loadData();
        
        btnUbah.setVisible(false);
        btnHapus.setVisible(false);
        btnBatal.setVisible(false);
    }
    
    private void setTabelModel() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("ID Buku");
    model.addColumn("Judul");
    model.addColumn("Pengarang");
    model.addColumn("ID Kategori");
    model.addColumn("Nama Kategori");
    model.addColumn("Tahun Terbit");
    model.addColumn("ID Penerbit");
    model.addColumn("Nama Penerbit");
    model.addColumn("jumlah halaman");
    model.addColumn("Stok");
    model.addColumn("Gambar");
    jTable1.setModel(model);
    }
     
    private void loadData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); 

    try {
        // 1. Ambil koneksi
        Connection conn = Koneksi.koneksi.getKoneksi();
        
        // 2. Cek apakah koneksi berhasil atau tidak
        if (conn == null) {
            System.out.println("Gagal terhubung ke database. Cek konfigurasi koneksi Anda.");
            return;
        }
        
        // 3. Eksekusi query dengan INNER JOIN untuk mengambil nama_kategori dan nama_penerbit
        String sql = "SELECT b.Id_buku, b.judul_buku, b.Pengarang, b.id_kategori, k.nama_kategori, "
                   + "b.id_penerbit, p.nama_penerbit, b.jumlah_halaman, b.stok, b.cover "
                   + "FROM buku b "
                   + "INNER JOIN kategori_buku k ON b.id_kategori = k.id_kategori "
                   + "INNER JOIN penerbit p ON b.id_penerbit = p.id_penerbit"; 
        
        PreparedStatement st = conn.prepareStatement(sql);
        ResultSet rs = st.executeQuery();
        
        int no = 1;
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("Id_buku"),
                rs.getString("judul_buku"),
                rs.getString("Pengarang"),
                rs.getString("id_kategori"),
                rs.getString("nama_kategori"),
                rs.getString("tahun_terbit"),
                rs.getString("id_penerbit"),
                rs.getString("nama_penerbit"), // Diambil dari tabel penerbit
                rs.getString("jumlah_halaman"),
                rs.getString("stok"),
                rs.getString("cover")
            });
        }
        
        // Tutup resources
        rs.close();
        st.close();
        
    } catch (Exception e) {
        System.out.println("Error pada loadData: " + e.toString());
        e.printStackTrace(); 
    }
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        tfCari = new palette.Custom_JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(50);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/peopleIconKecil.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Data Kategori Buku Perpustakaan");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Master Data > Kategori ");

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel13)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
            btnUbah.setVisible(false);
            btnHapus.setVisible(false);
            btnBatal.setVisible(false);
            btnTambah.setVisible(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
                                        
    String keyword = tfCari.getText().trim();
    
    // Jika kolom pencarian kosong, panggil loadData() untuk reset tampilan
    if (keyword.isEmpty()) {
        loadData();
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    try {
        java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
        // Query pencarian untuk tabel kategori_buku
        String sql = "SELECT * FROM kategori_buku " +
                     "WHERE ID_Kategori LIKE ? OR Nama_Kategori LIKE ? " +
                     "ORDER BY ID_Kategori ASC"; 

        java.sql.PreparedStatement st = conn.prepareStatement(sql);
        
        st.setString(1, "%" + keyword + "%"); 
        st.setString(2, "%" + keyword + "%");

        java.sql.ResultSet rs = st.executeQuery();

        int no = 1;
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("ID_Kategori"),
                rs.getString("Nama_Kategori"),
                rs.getString("Deskripsi")
            });
        }
        
        if (model.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            loadData();
        }
        
    } catch (Exception e) {
        System.out.println("Error pada btnCari: " + e.getMessage());
    }      // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (menuUtama != null) {
            menuUtama.showPanel(new menCRUDBuku());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int baris = jTable1.getSelectedRow();

        if (baris != -1) {
        // Mengambil data string dari tabel
        String idBuku = (jTable1.getValueAt(baris, 1) != null) ? jTable1.getValueAt(baris, 1).toString() : "";
        String judulBuku = (jTable1.getValueAt(baris, 2) != null) ? jTable1.getValueAt(baris, 2).toString() : "";
        String pengarang = (jTable1.getValueAt(baris, 3) != null) ? jTable1.getValueAt(baris, 3).toString() : "";
        String idKategori = (jTable1.getValueAt(baris, 4) != null) ? jTable1.getValueAt(baris, 4).toString() : "";
        String namaKategori = (jTable1.getValueAt(baris, 5) != null) ? jTable1.getValueAt(baris, 5).toString() : "";
        String tahunTerbit = (jTable1.getValueAt(baris, 6) != null) ? jTable1.getValueAt(baris, 6).toString() : "";
        String idPenerbit = (jTable1.getValueAt(baris, 7) != null) ? jTable1.getValueAt(baris, 7).toString() : "";
        String namaPenerbit = (jTable1.getValueAt(baris, 8) != null) ? jTable1.getValueAt(baris, 8).toString() : "";

        // Ambil data string lalu konversi ke int untuk jumlah halaman dan stok
        String strHalaman = (jTable1.getValueAt(baris, 9) != null) ? jTable1.getValueAt(baris, 9).toString() : "0";
        String strStok = (jTable1.getValueAt(baris, 10) != null) ? jTable1.getValueAt(baris, 10).toString() : "0";

        int jumlahHalaman = Integer.parseInt(strHalaman);
        int stok = Integer.parseInt(strStok);

        String cover = (jTable1.getValueAt(baris, 11) != null) ? jTable1.getValueAt(baris, 11).toString() : "";

        MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);

        if (menuUtama != null) {
            // Memanggil panel menuCRUDBuku dengan parameter yang sudah pas urutannya
            menuUtama.showPanel(new menCRUDBuku(idBuku, judulBuku, pengarang, idKategori, namaKategori, tahunTerbit, idPenerbit, namaPenerbit, jumlahHalaman, stok, cover));
        } else {
            System.out.println("Error: MenuUtama tidak ditemukan!");
        }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data buku di tabel terlebih dahulu!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    int baris = jTable1.getSelectedRow();
    
    if (baris != -1) {
        // Mengambil ID_Kategori dari kolom indeks 1
        String idKategori = jTable1.getValueAt(baris, 1).toString();
        
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus kategori dengan ID: " + idKategori + "?", 
                "Konfirmasi Hapus", 
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection conn = Koneksi.koneksi.getKoneksi();
                String sql = "DELETE FROM kategori_buku WHERE ID_Kategori = ?";
                java.sql.PreparedStatement st = conn.prepareStatement(sql);
                
                st.setString(1, idKategori);
                st.executeUpdate();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                
                // Refresh tabel dan kosongkan field jika ada fungsi batal
                loadData();
                // Jika Anda punya tombol batal, panggil fungsinya di sini
                // btnBatalActionPerformed(evt);
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih baris data kategori yang ingin dihapus di tabel!");
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            btnUbah.setVisible(true);
            btnHapus.setVisible(true);
            btnBatal.setVisible(true);
            btnTambah.setVisible(false);       
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private palette.Custom_JTextField tfCari;
    // End of variables declaration//GEN-END:variables
}
