/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Koneksi.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafli
 */
public class menuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    public menuDashboard() {
        initComponents();
        hitungData();
        loadTable();
    }
    private void hitungData() {
    try {
        Connection conn = Koneksi.koneksi.getKoneksi();
        Statement st = conn.createStatement();

        // 1. Hitung Anggota
        ResultSet rsAnggota = st.executeQuery("SELECT COUNT(*) FROM data_anggota");
        if (rsAnggota.next()) txtAnggota.setText(rsAnggota.getString(1));

        // 2. Hitung Stok Buku (Total buku di perpustakaan)
        ResultSet rsBuku = st.executeQuery("SELECT SUM(Stok) FROM buku");
        if (rsBuku.next()) txtBuku.setText(rsBuku.getString(1));

        // 3. Hitung Total Buku Sedang Dipinjam
        ResultSet rsPinjam = st.executeQuery("SELECT SUM(Jumlah_Pinjam) FROM peminjaman WHERE Tanggal_Kembali IS NULL OR Tanggal_Kembali = '0000-00-00'");
        if (rsPinjam.next()) txtPeminjaman.setText(rsPinjam.getString(1) != null ? rsPinjam.getString(1) : "0");

        // 4. Hitung Total Buku Sudah Kembali
        ResultSet rsKembali = st.executeQuery("SELECT SUM(Jumlah_Pinjam) FROM peminjaman WHERE Tanggal_Kembali IS NOT NULL AND Tanggal_Kembali != '0000-00-00'");
        if (rsKembali.next()) txtPengembalian.setText(rsKembali.getString(1) != null ? rsKembali.getString(1) : "0");

    } catch (Exception e) {
        System.out.println("Error hitungData: " + e.getMessage());
    }
}
    
    private void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("ID Pinjam");
        model.addColumn("Nama Anggota");
        model.addColumn("Judul Buku");
        model.addColumn("Jumlah");
        model.addColumn("Tgl Pinjam");
        model.addColumn("Tgl Kembali");
        model.addColumn("Status");

        try {
            Connection conn = Koneksi.koneksi.getKoneksi();
            String sql = "SELECT p.Id_Pinjam, a.Nama, b.Judul_Buku, p.Jumlah_Pinjam, p.Tanggal_Pinjam, p.Tanggal_Kembali " +
                         "FROM peminjaman p " +
                         "JOIN data_anggota a ON p.Nis = a.Nis " +
                         "JOIN buku b ON p.Id_Buku = b.Id_Buku";

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            int no = 1;
            while (rs.next()) {
                // PERBAIKAN: Gunakan penggabungan string biasa
                String formatID = "PJM" + rs.getString("Id_Pinjam");

                String tglKembali = rs.getString("Tanggal_Kembali");
                String status = (tglKembali == null || tglKembali.equals("0000-00-00")) ? "Sedang dipinjam" : "Sudah dikembalikan";

                model.addRow(new Object[]{
                    no++,
                    formatID,
                    rs.getString("Nama"),
                    rs.getString("Judul_Buku"),
                    rs.getString("Jumlah_Pinjam"),
                    rs.getString("Tanggal_Pinjam"),
                    (tglKembali == null || tglKembali.equals("0000-00-00")) ? "-" : tglKembali,
                    status
                });
            }
            tblDataDashboard.setModel(model);

            // Mengatur lebar kolom "No"
            tblDataDashboard.getColumnModel().getColumn(0).setPreferredWidth(30);

        } catch (Exception e) {
            System.out.println("Error loadTable: " + e.getMessage());
        }
}   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custom_JPanelRounded1 = new palette.Custom_JPanelRounded();
        jLabel1 = new javax.swing.JLabel();
        txtAnggota = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        custom_JPanelRounded2 = new palette.Custom_JPanelRounded();
        jLabel4 = new javax.swing.JLabel();
        txtBuku = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        custom_JPanelRounded3 = new palette.Custom_JPanelRounded();
        jLabel7 = new javax.swing.JLabel();
        txtPeminjaman = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        custom_JPanelRounded4 = new palette.Custom_JPanelRounded();
        jLabel10 = new javax.swing.JLabel();
        txtPengembalian = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataDashboard = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        custom_JPanelRounded1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Anggota");

        txtAnggota.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtAnggota.setForeground(new java.awt.Color(255, 255, 255));
        txtAnggota.setText("999");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/IconOrang.png"))); // NOI18N

        javax.swing.GroupLayout custom_JPanelRounded1Layout = new javax.swing.GroupLayout(custom_JPanelRounded1);
        custom_JPanelRounded1.setLayout(custom_JPanelRounded1Layout);
        custom_JPanelRounded1Layout.setHorizontalGroup(
            custom_JPanelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(custom_JPanelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtAnggota))
                .addGap(116, 116, 116))
            .addGroup(custom_JPanelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelRounded1Layout.createSequentialGroup()
                    .addContainerGap(99, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );
        custom_JPanelRounded1Layout.setVerticalGroup(
            custom_JPanelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(txtAnggota)
                .addContainerGap())
            .addGroup(custom_JPanelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelRounded1Layout.createSequentialGroup()
                    .addContainerGap(68, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(15, 15, 15)))
        );

        custom_JPanelRounded2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buku");

        txtBuku.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtBuku.setForeground(new java.awt.Color(255, 255, 255));
        txtBuku.setText("999");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/BookIcon.png"))); // NOI18N

        javax.swing.GroupLayout custom_JPanelRounded2Layout = new javax.swing.GroupLayout(custom_JPanelRounded2);
        custom_JPanelRounded2.setLayout(custom_JPanelRounded2Layout);
        custom_JPanelRounded2Layout.setHorizontalGroup(
            custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelRounded2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtBuku))
                .addGap(146, 146, 146))
            .addGroup(custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelRounded2Layout.createSequentialGroup()
                    .addContainerGap(128, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)))
        );
        custom_JPanelRounded2Layout.setVerticalGroup(
            custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(txtBuku)
                .addContainerGap())
            .addGroup(custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelRounded2Layout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(11, 11, 11)))
        );

        custom_JPanelRounded3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peminjaman");

        txtPeminjaman.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        txtPeminjaman.setText("999");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/IconPinjamBuku.png"))); // NOI18N

        javax.swing.GroupLayout custom_JPanelRounded3Layout = new javax.swing.GroupLayout(custom_JPanelRounded3);
        custom_JPanelRounded3.setLayout(custom_JPanelRounded3Layout);
        custom_JPanelRounded3Layout.setHorizontalGroup(
            custom_JPanelRounded3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(custom_JPanelRounded3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(custom_JPanelRounded3Layout.createSequentialGroup()
                        .addComponent(txtPeminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        custom_JPanelRounded3Layout.setVerticalGroup(
            custom_JPanelRounded3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(custom_JPanelRounded3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeminjaman)
                    .addComponent(jLabel19))
                .addContainerGap())
        );

        custom_JPanelRounded4.setBackground(new java.awt.Color(0, 102, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pengembalian");

        txtPengembalian.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        txtPengembalian.setText("999");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/IconKembaliBuku.png"))); // NOI18N

        javax.swing.GroupLayout custom_JPanelRounded4Layout = new javax.swing.GroupLayout(custom_JPanelRounded4);
        custom_JPanelRounded4.setLayout(custom_JPanelRounded4Layout);
        custom_JPanelRounded4Layout.setHorizontalGroup(
            custom_JPanelRounded4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded4Layout.createSequentialGroup()
                .addGroup(custom_JPanelRounded4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(custom_JPanelRounded4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtPengembalian)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(custom_JPanelRounded4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        custom_JPanelRounded4Layout.setVerticalGroup(
            custom_JPanelRounded4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(custom_JPanelRounded4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPengembalian)
                    .addComponent(jLabel16))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Master Data > Dashboard ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Riwayat Peminjaman Buku");

        tblDataDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDataDashboard.setRowHeight(50);
        jScrollPane1.setViewportView(tblDataDashboard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(custom_JPanelRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(custom_JPanelRounded2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(custom_JPanelRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(custom_JPanelRounded4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 215, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custom_JPanelRounded4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custom_JPanelRounded3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custom_JPanelRounded2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custom_JPanelRounded1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private palette.Custom_JPanelRounded custom_JPanelRounded1;
    private palette.Custom_JPanelRounded custom_JPanelRounded2;
    private palette.Custom_JPanelRounded custom_JPanelRounded3;
    private palette.Custom_JPanelRounded custom_JPanelRounded4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataDashboard;
    private javax.swing.JLabel txtAnggota;
    private javax.swing.JLabel txtBuku;
    private javax.swing.JLabel txtPeminjaman;
    private javax.swing.JLabel txtPengembalian;
    // End of variables declaration//GEN-END:variables
}
