/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import Koneksi.koneksi;
import java.sql.Connection;
import Tampilan.MenuUtama;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import Tampilan.DialongPilihPengembalian;
import View.menuCRUDPengembalian;

/**
 *
 * @author User
 */
public class MenuPengembalian extends javax.swing.JPanel {
    private void bersihkanForm(){
        txtIdPengembalian.setText("");
        txtTanggalKembali.setText("");
        txtIdPeminjaman.setText("");
        txtDenda.setText("");
        txtIdPengembalian.requestFocus();
}
    private void getpeminjaman() {
    String idPinjam = txtIdPeminjaman.getText().trim();
    if (idPinjam.isEmpty()) return;
    try {
        koneksi kon = new koneksi();
        java.sql.Connection conn = kon.getKoneksi();

        String sql = "SELECT p.Id_Pinjam, p.Tanggal_Pinjam, p.Tanggal_Kembali, " +
             "a.id_anggota, a.nama, " +
             "b.id_buku, b.judul, b.pengarang, b.penerbit " +
             "FROM peminjaman p " +
             "JOIN data_anggota a ON p.Nis = a.Nis " +
             "JOIN buku b ON p.Id_Buku = b.id_buku " +
             "WHERE p.Id_Pinjam = ?";
        
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, idPinjam);
        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtTanggalPinjam.setText(rs.getString("Tanggal_Pinjam"));
    txtTanggalKembali.setText(rs.getString("Tanggal_Kembali"));
    txtIdAnggota.setText(rs.getString("Nis"));
    txtNamaAnggota.setText(rs.getString("nama"));
    txtBuku.setText(rs.getString("id_buku"));
    txtJudul.setText(rs.getString("judul"));
    txtPengarang.setText(rs.getString("pengarang"));
    txtPenerbit.setText(rs.getString("penerbit"));
    hitungDenda();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID Peminjaman tidak ditemukan!");
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}/**
     * Creates new form MenuPengembalian
     */
    public MenuPengembalian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new palette.Custom_JButton();
        btnKembali = new palette.Custom_JButton();
        custom_JPanelRounded1 = new palette.Custom_JPanelRounded();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTanggal = new palette.Custom_JTextField();
        txtIdPengembalian = new palette.Custom_JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDenda = new palette.Custom_JTextField();
        txtIdAnggota = new palette.Custom_JTextField();
        txtTanggalPinjam = new palette.Custom_JTextField();
        txtNamaAnggota = new palette.Custom_JTextField();
        txtTanggalKembali = new palette.Custom_JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtJudul = new palette.Custom_JTextField();
        txtPengarang = new palette.Custom_JTextField();
        txtPenerbit = new palette.Custom_JTextField();
        txtBuku = new palette.Custom_JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtIdPeminjaman = new palette.Custom_JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        IconBuku = new javax.swing.JLabel();
        btnGetPeminjaman = new javax.swing.JButton();
        IconBuku1 = new javax.swing.JLabel();
        IconBuku2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText(" Menu pengembalian Buku Perpustakaan");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Transaksi > Pengembalian");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, 20));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 59, -1, -1));

        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 59, -1, -1));

        custom_JPanelRounded1.setRoundBottomLeft(20);
        custom_JPanelRounded1.setRoundBottomRight(20);
        custom_JPanelRounded1.setRoundTopLeft(20);
        custom_JPanelRounded1.setRoundTopRight(20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal");

        txtTanggal.setPlaceholder("Tanggal");

        txtIdPengembalian.setPlaceholder("ID");

        javax.swing.GroupLayout custom_JPanelRounded1Layout = new javax.swing.GroupLayout(custom_JPanelRounded1);
        custom_JPanelRounded1.setLayout(custom_JPanelRounded1Layout);
        custom_JPanelRounded1Layout.setHorizontalGroup(
            custom_JPanelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtIdPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        custom_JPanelRounded1Layout.setVerticalGroup(
            custom_JPanelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(custom_JPanelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(custom_JPanelRounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, 1010, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Peminjaman");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 221, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Pinjam");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 276, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Kembali");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 325, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Id Anggota");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Nama Anggota");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 434, -1, -1));

        txtDenda.setPlaceholder("Denda");
        txtDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDendaActionPerformed(evt);
            }
        });
        add(txtDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 130, -1));

        txtIdAnggota.setPlaceholder("ID Anggota");
        add(txtIdAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 374, 232, -1));

        txtTanggalPinjam.setPlaceholder("Tanggal Pinjam");
        add(txtTanggalPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 270, 232, -1));

        txtNamaAnggota.setPlaceholder("Nama Anggota");
        add(txtNamaAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 428, 232, -1));

        txtTanggalKembali.setPlaceholder("Tanggal Kembali");
        add(txtTanggalKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 319, 232, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Buku");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 47, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Judul");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Pengarang");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Penerbit");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        txtJudul.setPlaceholder("Judul");
        add(txtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 232, -1));

        txtPengarang.setPlaceholder("Pengarang");
        add(txtPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 232, -1));

        txtPenerbit.setPlaceholder("Penerbit");
        add(txtPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 232, -1));

        txtBuku.setPlaceholder("Buku");
        add(txtBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 230, -1));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 160, 200));

        txtIdPeminjaman.setPlaceholder("ID Peminjaman");
        add(txtIdPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 215, 190, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Denda");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setText("Info Denda");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        IconBuku.setBackground(new java.awt.Color(255, 255, 255));
        IconBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/transaksipengembalian.png"))); // NOI18N
        add(IconBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 50, 50));

        btnGetPeminjaman.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnGetPeminjaman.setText("...");
        btnGetPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetPeminjamanActionPerformed(evt);
            }
        });
        add(btnGetPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 35, 35));

        IconBuku1.setForeground(new java.awt.Color(240, 240, 240));
        IconBuku1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/penegmbalian.png"))); // NOI18N
        add(IconBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        IconBuku2.setBackground(new java.awt.Color(255, 255, 255));
        IconBuku2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/penegmbalian.png"))); // NOI18N
        add(IconBuku2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    // TODO add your handling code here: 
    String id_kembali = txtIdPengembalian.getText();
    String tgl_kembali = txtTanggalKembali.getText();
    String id_pinjam = txtIdPeminjaman.getText();
    String denda = txtDenda.getText();
    
    if(id_kembali.equals("") || tgl_kembali.equals("") || id_pinjam.equals("")){
     JOptionPane.showMessageDialog(null, "Data Belum Lengkap!");
    } else {
        try {
            String sql = "INSERT INTO pengembalian VALUES ('"+id_kembali+"', '"+tgl_kembali+"', '"+id_pinjam+"', '"+denda+"')";
            java.sql.Connection conn = koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            bersihkanForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Tersimpan:");
            
        }
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
    MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
    if (menuUtama != null) {
        menuUtama.showPanel(new menuCRUDPengembalian());
    }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnGetPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPeminjamanActionPerformed

    DialongPilihPengembalian dialog = new DialongPilihPengembalian(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true, null
    );
    dialog.setVisible(true);

    String idPinjam = dialog.getIdPeminjaman();
    if (idPinjam != null && !idPinjam.isEmpty()) {
        txtIdPeminjaman.setText(idPinjam);
        getpeminjaman();

}
    }//GEN-LAST:event_btnGetPeminjamanActionPerformed
    private void hitungDenda(){  
    try {
        String tglKembaliStr = txtTanggalKembali.getText();
        java.time.LocalDate tglKembali = java.time.LocalDate.parse(tglKembaliStr);
        java.time.LocalDate tglHariIni = java.time.LocalDate.now();

        long telat = java.time.temporal.ChronoUnit.DAYS.between(tglKembali, tglHariIni);

        if (telat > 0) {
            long totalDenda = telat * 500;
            txtDenda.setText(String.valueOf(totalDenda));
        } else {
            txtDenda.setText("0");
        }
    } catch (Exception e) {
        txtDenda.setText("0");
    }
    }
    private void txtDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDendaActionPerformed
        
    }//GEN-LAST:event_txtDendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconBuku;
    private javax.swing.JLabel IconBuku1;
    private javax.swing.JLabel IconBuku2;
    private javax.swing.JButton btnGetPeminjaman;
    private palette.Custom_JButton btnKembali;
    private palette.Custom_JButton btnSimpan;
    private palette.Custom_JPanelRounded custom_JPanelRounded1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private palette.Custom_JTextField txtBuku;
    private palette.Custom_JTextField txtDenda;
    private palette.Custom_JTextField txtIdAnggota;
    private palette.Custom_JTextField txtIdPeminjaman;
    private palette.Custom_JTextField txtIdPengembalian;
    private palette.Custom_JTextField txtJudul;
    private palette.Custom_JTextField txtNamaAnggota;
    private palette.Custom_JTextField txtPenerbit;
    private palette.Custom_JTextField txtPengarang;
    private palette.Custom_JTextField txtTanggal;
    private palette.Custom_JTextField txtTanggalKembali;
    private palette.Custom_JTextField txtTanggalPinjam;
    // End of variables declaration//GEN-END:variables
}
