/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import View.menuCRUDPengembalian;
import Koneksi.koneksi;
import Tampilan.MenuUtama;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class menuPengembalian extends javax.swing.JPanel {

    /**
     * Creates new form menuCRUDPengembalian
     */
    public menuPengembalian() {
        initComponents();
       insertData();
       tampilData("");
    }
    private void insertData() {
    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    
    try {
        koneksi kon = new koneksi();
        java.sql.Connection conn = kon.getKoneksi();
        
        String sql = "SELECT id_pengembalian, tgl_pengembalian, " +
             "id_peminjaman, point " +
             "FROM pengembalian";
        
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        java.sql.ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_pengembalian"),
                rs.getString("tgl_pengembalian"),
                rs.getString("id_peminjaman"),
                rs.getString("point")
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    public void tampilData(String cari) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pengembalian");
    model.addColumn("Tanggal Pengembalian");
    model.addColumn("ID Peminjaman");
    model.addColumn("Denda"); // Sesuai kolom ke-4 di design Anda

    try {
        Koneksi.koneksi kon = new Koneksi.koneksi();
        java.sql.Connection conn = kon.getKoneksi();
        
        // Query SQL menggunakan LIKE untuk mencari berdasarkan ID Pengembalian atau ID Peminjaman
        String sql = "SELECT id_pengembalian, tgl_pengembalian, id_peminjaman, denda " +
                     "FROM pengembalian " +
                     "WHERE id_pengembalian LIKE ? OR id_peminjaman LIKE ?";
        
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + cari + "%");
        ps.setString(2, "%" + cari + "%");
        
        java.sql.ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_pengembalian"),
                rs.getString("tgl_pengembalian"),
                rs.getString("id_peminjaman"),
                rs.getString("denda") // Menampilkan nilai denda/petugas sesuai struktur database Anda
            });
        }
        
        // Sesuaikan jTable1 dengan nama variabel tabel utama Anda di halaman ini
        jTable1.setModel(model);
        
    } catch (Exception e) {
        System.out.println("Error memuat tabel pengembalian: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTambah = new palette.Custom_JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSerch = new palette.Custom_JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jCombobox = new javax.swing.JComboBox<>();
        btn3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        IconBuku1 = new javax.swing.JLabel();
        IconBuku = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Data Pengembalian Buku Perpustakaan");

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Transaksi > Pengembalian");

        txtSerch.setPlaceholder("Serch");
        txtSerch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSerchCaretUpdate(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pengembalian", "Tanggal Pengembalian", "ID Peminjaman ", "Petugas"
            }
        ));
        jTable1.setRowHeight(50);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Halaman 1 Dari Total Data 2");

        jButton1.setText("First Page");

        btn2.setText("<");

        jCombobox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", " " }));
        jCombobox.setToolTipText("");

        btn3.setText(">");

        jButton4.setText("List Page");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        IconBuku1.setForeground(new java.awt.Color(240, 240, 240));
        IconBuku1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/penegmbalian.png"))); // NOI18N

        IconBuku.setBackground(new java.awt.Color(255, 255, 255));
        IconBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/transaksipengembalian.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IconBuku1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(IconBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn2)
                        .addGap(18, 18, 18)
                        .addComponent(jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconBuku1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn2)
                    .addComponent(jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3)
                    .addComponent(jButton4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        MenuUtama menuUtama = (MenuUtama) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (menuUtama != null){
      menuUtama.showPanel(new menuCRUDPengembalian());
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtSerchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSerchCaretUpdate
        // TODO add your handling code here:
        tampilData(txtSerch.getText());
    }//GEN-LAST:event_txtSerchCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconBuku;
    private javax.swing.JLabel IconBuku1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private palette.Custom_JButton btnTambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private palette.Custom_JTextField txtSerch;
    // End of variables declaration//GEN-END:variables
}
