/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class DialongPilihPengembalian extends javax.swing.JDialog {
private String idPeminjaman;
    /**
     * Creates new form DialongPilihPinjam
     */
    private View.menuPengembalian parentForm;

public DialongPilihPengembalian(java.awt.Frame owner, boolean modal, View.menuPengembalian parent) {
    super(owner, modal);
    this.parentForm = parent;
    initComponents();
    loadData("");
    }
    public String getIdPeminjaman() {
        return idPeminjaman;
    }
private void loadData(String keyword) {
    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    
    try {
        Koneksi.koneksi kon = new Koneksi.koneksi();
        java.sql.Connection conn = kon.getKoneksi();
        
       String sql = "SELECT p.Id_Pinjam, p.Tanggal_Pinjam, p.Tanggal_Kembali, " +
             "a.nama FROM peminjaman p " +
             "JOIN data_anggota a ON p.Nis = a.Nis " +
             "WHERE p.Id_Pinjam LIKE ? OR a.nama LIKE ?";
        
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        java.sql.ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("Id_Pinjam"),
                rs.getString("Tanggal_Pinjam"),
                rs.getString("Tanggal_Kembali"),
                rs.getString("nama")
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
public void tampilData(String cari) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pinjam");
    model.addColumn("Tanggal Pinjam");
    model.addColumn("Tanggal Kembali");

    try {
        Koneksi.koneksi kon = new Koneksi.koneksi();
        java.sql.Connection conn = kon.getKoneksi();
        
        // Query mendeteksi inputan pencarian berdasarkan id_peminjaman
        String sql = "SELECT id_peminjaman, tgl_peminjaman, tgl_kembali FROM peminjaman WHERE id_peminjaman LIKE ?";
        
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + cari + "%"); // Menangkap teks pencarian secara fleksibel
        
        java.sql.ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_peminjaman"),
                rs.getString("tgl_peminjaman"),
                rs.getString("tgl_kembali")
            });
        }
        
        // Ganti jTable1 sesuai dengan nama variabel komponen tabel di design Anda
        jTable1.setModel(model); 
        
    } catch (Exception e) {
        System.out.println("Error memuat tabel pencarian: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFrist = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSerch = new palette.Custom_JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Data Peminjam");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Halaman 1 Dari Total Data 5");

        btnFrist.setText("Frist");

        jButton1.setText("<");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));

        jButton2.setText(">");

        jButton3.setText("Last");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Transaksi Peminjaman");

        txtSerch.setPlaceholder("Serch");
        txtSerch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSerchCaretUpdate(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pinjam", "Tanggal PInjam", "Tanggal Kembali", "Nama Anggota"
            }
        ));
        jTable1.setRowHeight(50);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 553, Short.MAX_VALUE)
                .addComponent(btnFrist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addGap(490, 490, 490))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(354, 354, 354))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
   // Menggunakan sekali klik agar lebih responsif
    int row = jTable1.getSelectedRow();
    if (row >= 0) {
        String idPinjam = jTable1.getValueAt(row, 0).toString();
        String tglPinjam = jTable1.getValueAt(row, 1) != null ? jTable1.getValueAt(row, 1).toString() : "";
        String tglKembali = jTable1.getValueAt(row, 2) != null ? jTable1.getValueAt(row, 2).toString() : "";
        
        if (parentForm != null) {
            try {
                Koneksi.koneksi kon = new Koneksi.koneksi();
                java.sql.Connection conn = kon.getKoneksi();
                
                // Menambahkan LIMIT 1 agar baris data ganda tidak membuat textfield crash
                String sql = "SELECT p.Nis, a.nama, dp.Id_Buku, b.Judul_Buku, b.Pengarang, pb.nama_penerbit " +
                             "FROM peminjaman p " +
                             "JOIN data_anggota a ON p.Nis = a.Nis " +
                             "JOIN detail_pinjam dp ON p.Id_Pinjam = dp.Id_Pinjam " +
                             "JOIN buku b ON dp.Id_Buku = b.Id_Buku " +
                             "JOIN penerbit pb ON b.id_penerbit = pb.id_penerbit " +
                             "WHERE p.Id_Pinjam = ? " +
                             "LIMIT 1"; 
                
                java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, idPinjam);
                java.sql.ResultSet rs = ps.executeQuery();
                
                if (rs.next()) {
                    // Mengirimkan data ke form menuPengembalian
                    parentForm.itemTerpilihPeminjaman(
                        idPinjam, 
                        tglPinjam, 
                        tglKembali,
                        rs.getString("Nis"), 
                        rs.getString("nama"),
                        rs.getString("Id_Buku"), 
                        rs.getString("Judul_Buku"),
                        rs.getString("Pengarang"), 
                        rs.getString("nama_penerbit")
                    );
                    this.dispose(); // Tutup pop-up jDialog setelah sukses mengirim
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Relasi data gagal! Periksa apakah data Anggota atau Penerbit di database terhapus.");
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Error: " + e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Hubungan ke Form Utama (parentForm) kosong/null!");
        }
    }

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtSerchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSerchCaretUpdate
        // TODO add your handling code here:                                    
      loadData(txtSerch.getText());
    }//GEN-LAST:event_txtSerchCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialongPilihPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialongPilihPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialongPilihPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialongPilihPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               DialongPilihPengembalian dialog = new DialongPilihPengembalian(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFrist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private palette.Custom_JTextField txtSerch;
    // End of variables declaration//GEN-END:variables
}
