/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;


/**
 *
 * @author rafli
 */
public class FormLogin extends javax.swing.JFrame {
    
    int xx, xy;
    private Connection conn;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLogin.class.getName());

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        conn = Koneksi.getConnection;
        this.setLocationRelativeTo(null);
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        setActionButton();
        
        // untuk Logo Utama //
        try {
        javax.swing.ImageIcon iconAsli = new javax.swing.ImageIcon(getClass().getResource("/gambar/LoginPagePng.png"));
        
        // GANTI ANGKA DI BAWAH INI sesuai ukuran JLabel kamu di menu Design
        int targetWidth = 333;  
        int targetHeight = 335; 
        
        // Melakukan scaling smooth dengan ukuran pasti
        java.awt.Image imgSelesai = iconAsli.getImage().getScaledInstance(targetWidth, targetHeight, java.awt.Image.SCALE_SMOOTH);
        
        jLabelIcon.setIcon(new javax.swing.ImageIcon(imgSelesai));
        
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
        
        // untuk Logo Mata
}
    @SuppresWarnings("unchecked")
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {
        xx = evt.getX();
        xy = evt.getY();
        
    }
    
    private void formMouseDragged(java.awt.event.MouseEvent evt) {
        int x = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custom_JPanelRounded1 = new palette.Custom_JPanelRounded();
        custom_JPanelRounded2 = new palette.Custom_JPanelRounded();
        jLabelIcon = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        t_username = new palette.Custom_JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hideEye = new javax.swing.JLabel();
        t_password = new palette.Custom_JPasswordField();
        btn_login = new palette.Custom_JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        custom_JPanelRounded1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custom_JPanelRounded2.setBackground(new java.awt.Color(224, 234, 255));
        custom_JPanelRounded2.setRoundBottomLeft(0);
        custom_JPanelRounded2.setRoundTopLeft(0);

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/LoginPagePng.png"))); // NOI18N

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setText("X");

        javax.swing.GroupLayout custom_JPanelRounded2Layout = new javax.swing.GroupLayout(custom_JPanelRounded2);
        custom_JPanelRounded2.setLayout(custom_JPanelRounded2Layout);
        custom_JPanelRounded2Layout.setHorizontalGroup(
            custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel))
        );
        custom_JPanelRounded2Layout.setVerticalGroup(
            custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(custom_JPanelRounded2Layout.createSequentialGroup()
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        custom_JPanelRounded1.add(custom_JPanelRounded2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 0, -1, 388));

        t_username.setForeground(new java.awt.Color(153, 153, 153));
        t_username.addActionListener();
        custom_JPanelRounded1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, 350, 41));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Selamat Datang");
        custom_JPanelRounded1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Password");
        custom_JPanelRounded1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 164, -1, -1));

        hideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/eyesIconfit.png"))); // NOI18N
        hideEye.addMouseListener();
        custom_JPanelRounded1.add(hideEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 30, 40));

        t_password.setForeground(new java.awt.Color(153, 153, 153));
        t_password.addActionListener();
        custom_JPanelRounded1.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 192, 350, 41));

        btn_login.setText("LOGIN");
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_login.addMouseListener();
        btn_login.addKeyListener();
        custom_JPanelRounded1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 258, 350, 41));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Username");
        custom_JPanelRounded1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 77, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Halo,");
        custom_JPanelRounded1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(custom_JPanelRounded1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(custom_JPanelRounded1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void btn_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_loginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginKeyPressed

    private void hideEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideEyeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hideEyeMouseClicked

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private palette.Custom_JButton btn_login;
    private palette.Custom_JPanelRounded custom_JPanelRounded1;
    private palette.Custom_JPanelRounded custom_JPanelRounded2;
    private javax.swing.JLabel hideEye;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelIcon;
    private palette.Custom_JPasswordField t_password;
    private palette.Custom_JTextField t_username;
    // End of variables declaration//GEN-END:variables

    private void setActionButton() {
         eye.addMouseListener(new MouseAdapter(){})
            @Override
             public void mouseClicked(MousedEvent e) {
                 hideEye.setVisible(false);
                 hideEye.setVisible(true);
                 t_password.setEchoChar((char)0);
             }     
             ()};

             hideEye.addMouseListener(new MouseAdapter(){})
            @Override
             public void mouseClicked(MousedEvent e) {
                 eye.setVisible(true);
                 hideEye.setVisible(false);
                 t_password.setEchoChar('*');
             }     
             ()};

             btn_login.addMouseListener(new MouseAdapter(){
                @Override
                public void mouseClicked(MouseEvent e) {
                    prosesLogin();
                }
             });

             btn_cancel.addMouseListener(new MouseAdapter(){
                @Override
                public void mouseClicked(MouseEvent e) {
                    dispose();
                    System.exit(0);
                }
             });

             t_password.addKeyListener(new KeyAdapter(){
                @Override
                public void keyPressed(KeyEvent e){
                    if(e.getKeyCode() == KeyEvent.VK_ENTER){
                        btn_login.doClick();
                    }
                }
             });


             private String getMd5java(String, messge) {
                String digest = null;
                try {
                    MessageDigest md = MessageDigest.getInstance("MD5");
                    byte[] hash = md.digest(message.getBytes("UTF-8"));

                    StringBuilder sb  = new StringBuilder(2 * hash.lenght);
                    for(byte b : hash){
                        sb.append(String.format("%20", b & 0xff));
                    }
                    digest = sb.toString();
                    
            } catch (Exception e) {
                Logger.getLogger(formLogin.clss.getName()).log(Level.SEVERE, null, e);
            }
                
                return digest;
        }

        private boolean validasiInput(){
            boolean valid  = false;
            if(t_username.getText().trim().isEmpty){
                JOptionPane.showMessageDialog(this, "Username tidak boleh kosong");
            }else if(t_password.getText().trim().isEmpty){
                JOptionPane.showMessageDialog(this, "Password tidak boleh kosong");
            }else{
                valid = true;
            }
            return valid;
        }

        private boolean checkLogin(String username, String password){
            if(conn != null){
                try {
                    String sql = "SELECT * FROM user WHERE Username=? AND Password=?";
                    PreparedStatement st = conn.prepareStatement(sql);
                    st.setString(1, username);
                    st.setString(2, password);
                    
                    ResultSet rs = st.executeQuery():
                    if(rs.next()) {
                        return true;
                    }
                }catch (SQLException e) {
                }
            }

            return false;
        }

        private void prosesLogin() {
            if(validasiInput()){
                String username = t_username.getText();
                String password = new String(t_password.getPassword());
                String hashedPassword = getMd5java(password);

                if(checkLogin(username, hashedPassword)){
                    MenuUtama mn = new MenuUtama();
                    mn.setVisible(true);
                    mn.revalidate();

                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Username atau Password salah","pesan",
                    JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }


}
