package Tampilan;

import Tampilan.MenuUtama;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import Menu.MenuGantIPassword;

/**
 *
 * @author imam
 */
public class MenuProfile extends java.awt.Dialog {
    private MenuUtama menuUtama;

    public MenuProfile(java.awt.Frame parent, boolean modal, MenuUtama menuUtama) {
        super(parent, modal);
        initComponents();
        this.menuUtama = menuUtama;
        
        setSize(400, 310);
        setLocationRelativeTo(parent);
        
        // Ganti Password
        pn_GantiPw.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                pn_GantiPw.setBackground(new Color(240, 240, 240));

                if (menuUtama != null) {
                    menuUtama.showPanel(new MenuGantIPassword());
                }
                setVisible(false);
                dispose();
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                pn_GantiPw.setBackground(new Color(250, 250, 250));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                pn_GantiPw.setBackground(new Color(255, 255, 255));
            }
        });
        
        // Logout 
        pn_Logout.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(
                    null,
                    "Apakah Anda yakin ingin logout?",
                    "Konfirmasi Logout",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE
                );
                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    setVisible(false);
                    dispose();
                    if (menuUtama != null) {
                        menuUtama.dispose();
                    }
                    new FormLogin().setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pn_Logout = new javax.swing.JPanel();
        iconLogout = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        pn_GantiPw = new javax.swing.JPanel();
        iconGantiPw = new javax.swing.JLabel();
        lblGantiPw = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_Logout.setBackground(new java.awt.Color(255, 0, 0));
        pn_Logout.setForeground(new java.awt.Color(255, 0, 0));

        iconLogout.setBackground(new java.awt.Color(255, 255, 255));
        iconLogout.setForeground(new java.awt.Color(255, 255, 255));
        iconLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logout.png"))); // NOI18N

        lblLogout.setBackground(new java.awt.Color(255, 255, 255));
        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Logout");

        javax.swing.GroupLayout pn_LogoutLayout = new javax.swing.GroupLayout(pn_Logout);
        pn_Logout.setLayout(pn_LogoutLayout);
        pn_LogoutLayout.setHorizontalGroup(
            pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LogoutLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(iconLogout)
                .addGap(28, 28, 28)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pn_LogoutLayout.setVerticalGroup(
            pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LogoutLayout.createSequentialGroup()
                .addGroup(pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_LogoutLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(iconLogout))
                    .addGroup(pn_LogoutLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblLogout)))
                .addGap(10, 10, 10))
        );

        jPanel1.add(pn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 400, -1));

        pn_GantiPw.setBackground(new java.awt.Color(255, 255, 255));
        pn_GantiPw.setForeground(new java.awt.Color(255, 255, 255));

        iconGantiPw.setBackground(new java.awt.Color(255, 255, 255));
        iconGantiPw.setForeground(new java.awt.Color(255, 255, 255));
        iconGantiPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ganti_pw.png"))); // NOI18N

        lblGantiPw.setBackground(new java.awt.Color(51, 102, 255));
        lblGantiPw.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGantiPw.setForeground(new java.awt.Color(51, 102, 255));
        lblGantiPw.setText("Ganti Password");

        javax.swing.GroupLayout pn_GantiPwLayout = new javax.swing.GroupLayout(pn_GantiPw);
        pn_GantiPw.setLayout(pn_GantiPwLayout);
        pn_GantiPwLayout.setHorizontalGroup(
            pn_GantiPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GantiPwLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(iconGantiPw)
                .addGap(28, 28, 28)
                .addComponent(lblGantiPw, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pn_GantiPwLayout.setVerticalGroup(
            pn_GantiPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GantiPwLayout.createSequentialGroup()
                .addGroup(pn_GantiPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_GantiPwLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(iconGantiPw))
                    .addGroup(pn_GantiPwLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblGantiPw)))
                .addGap(10, 10, 10))
        );

        jPanel1.add(pn_GantiPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuProfile dialog = new MenuProfile(new java.awt.Frame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconGantiPw;
    private javax.swing.JLabel iconLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGantiPw;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JPanel pn_GantiPw;
    private javax.swing.JPanel pn_Logout;
    // End of variables declaration//GEN-END:variables
}