/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.nio.file.Files;
import java.io.IOException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.filechooser.FileNameExtensionFilter;
import Koneksi.koneksi; // Sesuaikan dengan package koneksi Anda

/**
 *
 * @author Elitebook Pro
 */
public class menubuku extends javax.swing.JPanel {

    // Variabel untuk menampung ID relasi database
    private String idKategori;
    private String idPenerbit;
    public menubuku() {
        initComponents();
        initComboBoxData(); // Mengisi data combobox saat form pertama kali dimuat
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        cbxtahun = new javax.swing.JComboBox<>();
        rxrimagepatcht = new java.awt.TextField();
        label7 = new java.awt.Label();
        btnbrowerser = new javax.swing.JButton();
        lblgambar = new javax.swing.JLabel();
        btnsmpn = new javax.swing.JButton();
        btnvtl = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtpengarang = new javax.swing.JTextField();
        cbxkategori = new javax.swing.JComboBox<>();
        cbxpenerbit = new javax.swing.JComboBox<>();

        jTextField2.setText("TAMBAHAN ");

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("ID");

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("JUDUL");

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("PENGARANG");

        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setText("TAHUN");

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setText("KATAGORI");

        rxrimagepatcht.setEnabled(false);
        rxrimagepatcht.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rxrimagepatcht.setText("image patch");
        rxrimagepatcht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rxrimagepatchtActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setText("PENERBIT");

        btnbrowerser.setText("jButton1");
        btnbrowerser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowerserActionPerformed(evt);
            }
        });

        lblgambar.setText(".");
        lblgambar.setOpaque(true);

        btnsmpn.setText("SIMPAN");

        btnvtl.setText("BATAL");

        txtid.setText("id");

        txtjudul.setText("judul");

        txtpengarang.setText("pengarang");

        cbxpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxpenerbitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117)
                .addComponent(lblgambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(rxrimagepatcht, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnbrowerser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnsmpn)
                        .addGap(33, 33, 33)
                        .addComponent(btnvtl))
                    .addComponent(cbxpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbxtahun, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsmpn)
                            .addComponent(btnvtl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblgambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rxrimagepatcht, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbrowerser))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxtahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        label3.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
   private void initComboBoxData() {
    // 1. AMBIL DATA KATEGORI
        try {
            DefaultComboBoxModel<String> modelKat = new DefaultComboBoxModel<>();
            modelKat.addElement("- Pilih Kategori -");
            
            Connection conn = koneksi.getKoneksi(); 
            String sql = "SELECT id_kategori, nama_kategori FROM kategori";
            Statement st = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()) {
                modelKat.addElement(rs.getString("nama_kategori"));
            }
            cbxkategori.setModel(modelKat);
            
            // Logika mengambil ID Kategori saat nama kategori dipilih
            final ResultSet rsKat = rs; 
            cbxkategori.addActionListener(e -> {
                int selectedIndex = cbxkategori.getSelectedIndex(); 
                if (selectedIndex > 0) {
                    try {
                        rsKat.absolute(selectedIndex);
                        idKategori = rsKat.getString("id_kategori");
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            });
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal meload kategori: " + e.getMessage());
        }

        // 2. AMBIL DATA PENERBIT
        try {
            DefaultComboBoxModel<String> modelPen = new DefaultComboBoxModel<>();
            modelPen.addElement("- Pilih Penerbit -");
            
            Connection conn = koneksi.getKoneksi();
            String sql = "SELECT id_penerbit, nama_penerbit FROM penerbit";
            Statement st = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()) {
                modelPen.addElement(rs.getString("nama_penerbit"));
            }
            cbxpenerbit.setModel(modelPen);
            
            // Logika mengambil ID Penerbit saat nama penerbit dipilih
            final ResultSet rsPen = rs; 
            cbxpenerbit.addActionListener(e -> {
                int selectedIndex = cbxpenerbit.getSelectedIndex();
                if (selectedIndex > 0) {
                    try {
                        rsPen.absolute(selectedIndex);
                        idPenerbit = rsPen.getString("id_penerbit");
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            });
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal meload penerbit: " + e.getMessage());
        }
    }
    private void rxrimagepatchtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rxrimagepatchtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rxrimagepatchtActionPerformed
     private void getKategori() {
        try {
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("Pilih Kategori");

            Connection conn = Koneksi.koneksi.getKoneksi(); 
            String sql = "SELECT id_kategori, nama_kategori FROM kategori";
            PreparedStatement st = conn.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                String namaKategori = rs.getString("nama_kategori");
                model.addElement(namaKategori);
            }
            cbxkategori.setModel(model);

            final ResultSet rsKat = rs;
            cbxkategori.addActionListener(e -> {
                int selectIndex = cbxkategori.getSelectedIndex();
                if (selectIndex > 0) {
                    try {
                        rsKat.absolute(selectIndex);
                        idKategori = rsKat.getString("id_kategori");
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            });
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
     private void getPenerbit() {
        try {
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("Pilih Penerbit");

            // Perbaikan 1: Mendeklarasikan koneksi database terlebih dahulu
            Connection conn = Koneksi.koneksi.getKoneksi();
            String sql = "SELECT id_penerbit, nama_penerbit FROM penerbit";
            PreparedStatement st = conn.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                String namaPenerbit = rs.getString("nama_penerbit");
                model.addElement(namaPenerbit);
            }

            cbxpenerbit.setModel(model);
            
            // Perbaikan 2: Salin ke variabel final agar aman di dalam lambda event listener
            final ResultSet rsPen = rs;
            cbxpenerbit.addActionListener(e -> {
                int selectIndex = cbxpenerbit.getSelectedIndex();

                if (selectIndex > 0) {
                    try {
                        rsPen.absolute(selectIndex);
                        idPenerbit = rsPen.getString("id_penerbit");
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            });
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void getImage() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Gambar (JPG, PNG, JPEG)", "jpg", "png", "jpeg");
        chooser.setFileFilter(filter);

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String path = file.getAbsolutePath();
            rxrimagepatcht.setText(path);

            try {
                byte[] imgBytes = Files.readAllBytes(file.toPath());
                ImageIcon imageIcon = new ImageIcon(imgBytes);
                
                int labelWidth = lblgambar.getWidth();
                int labelHeight = lblgambar.getHeight();
                int imageWidth = imageIcon.getIconWidth();
                int imageHeight = imageIcon.getIconHeight();

                double scaleX = (double) labelWidth / (double) imageWidth;
                double scaleY = (double) labelHeight / (double) imageHeight;
                double scale = Math.min(scaleX, scaleY);

                Image img = imageIcon.getImage().getScaledInstance(
                        (int) (scale * imageWidth), 
                        (int) (scale * imageHeight), 
                        Image.SCALE_SMOOTH
                );
                
                lblgambar.setIcon(new ImageIcon(img));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    
    
    
    private void btnbrowerserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowerserActionPerformed
                                                  
    getImage();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbrowerserActionPerformed

    private void cbxpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxpenerbitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbrowerser;
    private javax.swing.JButton btnsmpn;
    private javax.swing.JButton btnvtl;
    private javax.swing.JComboBox<String> cbxkategori;
    private javax.swing.JComboBox<String> cbxpenerbit;
    private javax.swing.JComboBox<String> cbxtahun;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label7;
    private javax.swing.JLabel lblgambar;
    private java.awt.TextField rxrimagepatcht;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtpengarang;
    // End of variables declaration//GEN-END:variables
}
