/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import View.menuDashboard;
import View.menuAnggota;
import View.MenuPengembalian;
/**
 *
 * @author rafli
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        pUtama.setLayout(new java.awt.BorderLayout());
        BpnlDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BpnlAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BpnlPengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BpnlAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            BpnlAnggotaMouseClicked(evt);
        }
    });
        BpnlPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPengembalian form = new MenuPengembalian();
                form.setVisible(true);
            }
        });
    }
});
    }
    
    public void showPanel(javax.swing.JPanel panel){
        pUtama.removeAll();
        pUtama.add(panel, java.awt.BorderLayout.CENTER);
        pUtama.repaint();
        pUtama.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pKiri = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        IconBuku = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BpnlDashboard = new javax.swing.JPanel();
        IconDashboard = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BpnlAnggota = new javax.swing.JPanel();
        IconDashboard1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BpnlBuku = new javax.swing.JPanel();
        IconDashboard2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BpnlKategori = new javax.swing.JPanel();
        IconDashboard3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BpnlPenerbit = new javax.swing.JPanel();
        IconDashboard4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BpnlPetugas = new javax.swing.JPanel();
        IconDashboard5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BpnlPeminjaman = new javax.swing.JPanel();
        IconDashboard6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BpnlPengembalian = new javax.swing.JPanel();
        IconDashboard7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BpnlLprPinjam = new javax.swing.JPanel();
        IconDashboard8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BpnlLprPengembalian = new javax.swing.JPanel();
        IconDashboard9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pKanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pDasar = new javax.swing.JPanel();
        pUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pKiri.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        IconBuku.setBackground(new java.awt.Color(255, 255, 255));
        IconBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/IconBuku.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IconBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IconBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Perpustakaan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("SDN 05 Pagi Bidaracina");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("MASTER DATA");

        BpnlDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BpnlDashboardMouseClicked(evt);
            }
        });

        IconDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Dashboard");

        javax.swing.GroupLayout BpnlDashboardLayout = new javax.swing.GroupLayout(BpnlDashboard);
        BpnlDashboard.setLayout(BpnlDashboardLayout);
        BpnlDashboardLayout.setHorizontalGroup(
            BpnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlDashboardLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlDashboardLayout.setVerticalGroup(
            BpnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlDashboardLayout.createSequentialGroup()
                .addGroup(BpnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlDashboardLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard))
                    .addGroup(BpnlDashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(10, 10, 10))
        );

        BpnlAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BpnlAnggotaMouseClicked(evt);
            }
        });

        IconDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Anggota");

        javax.swing.GroupLayout BpnlAnggotaLayout = new javax.swing.GroupLayout(BpnlAnggota);
        BpnlAnggota.setLayout(BpnlAnggotaLayout);
        BpnlAnggotaLayout.setHorizontalGroup(
            BpnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlAnggotaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard1)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlAnggotaLayout.setVerticalGroup(
            BpnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlAnggotaLayout.createSequentialGroup()
                .addGroup(BpnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlAnggotaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard1))
                    .addGroup(BpnlAnggotaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(10, 10, 10))
        );

        IconDashboard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Buku");

        javax.swing.GroupLayout BpnlBukuLayout = new javax.swing.GroupLayout(BpnlBuku);
        BpnlBuku.setLayout(BpnlBukuLayout);
        BpnlBukuLayout.setHorizontalGroup(
            BpnlBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlBukuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard2)
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlBukuLayout.setVerticalGroup(
            BpnlBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlBukuLayout.createSequentialGroup()
                .addGroup(BpnlBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlBukuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard2))
                    .addGroup(BpnlBukuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(10, 10, 10))
        );

        IconDashboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Kategori");

        javax.swing.GroupLayout BpnlKategoriLayout = new javax.swing.GroupLayout(BpnlKategori);
        BpnlKategori.setLayout(BpnlKategoriLayout);
        BpnlKategoriLayout.setHorizontalGroup(
            BpnlKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlKategoriLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard3)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlKategoriLayout.setVerticalGroup(
            BpnlKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlKategoriLayout.createSequentialGroup()
                .addGroup(BpnlKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlKategoriLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard3))
                    .addGroup(BpnlKategoriLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(10, 10, 10))
        );

        IconDashboard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Penerbit");

        javax.swing.GroupLayout BpnlPenerbitLayout = new javax.swing.GroupLayout(BpnlPenerbit);
        BpnlPenerbit.setLayout(BpnlPenerbitLayout);
        BpnlPenerbitLayout.setHorizontalGroup(
            BpnlPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlPenerbitLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard4)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlPenerbitLayout.setVerticalGroup(
            BpnlPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlPenerbitLayout.createSequentialGroup()
                .addGroup(BpnlPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlPenerbitLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard4))
                    .addGroup(BpnlPenerbitLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(10, 10, 10))
        );

        IconDashboard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Petugas");

        javax.swing.GroupLayout BpnlPetugasLayout = new javax.swing.GroupLayout(BpnlPetugas);
        BpnlPetugas.setLayout(BpnlPetugasLayout);
        BpnlPetugasLayout.setHorizontalGroup(
            BpnlPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlPetugasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard5)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlPetugasLayout.setVerticalGroup(
            BpnlPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlPetugasLayout.createSequentialGroup()
                .addGroup(BpnlPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlPetugasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard5))
                    .addGroup(BpnlPetugasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGap(10, 10, 10))
        );

        IconDashboard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Peminjaman");

        javax.swing.GroupLayout BpnlPeminjamanLayout = new javax.swing.GroupLayout(BpnlPeminjaman);
        BpnlPeminjaman.setLayout(BpnlPeminjamanLayout);
        BpnlPeminjamanLayout.setHorizontalGroup(
            BpnlPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlPeminjamanLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard6)
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlPeminjamanLayout.setVerticalGroup(
            BpnlPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlPeminjamanLayout.createSequentialGroup()
                .addGroup(BpnlPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlPeminjamanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard6))
                    .addGroup(BpnlPeminjamanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGap(10, 10, 10))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("TRANSAKSI");

        IconDashboard7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Pengembalian");

        javax.swing.GroupLayout BpnlPengembalianLayout = new javax.swing.GroupLayout(BpnlPengembalian);
        BpnlPengembalian.setLayout(BpnlPengembalianLayout);
        BpnlPengembalianLayout.setHorizontalGroup(
            BpnlPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlPengembalianLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard7)
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(60, 60, 60))
        );
        BpnlPengembalianLayout.setVerticalGroup(
            BpnlPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlPengembalianLayout.createSequentialGroup()
                .addGroup(BpnlPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlPengembalianLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard7))
                    .addGroup(BpnlPengembalianLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addGap(10, 10, 10))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("LAPORAN");

        BpnlLprPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BpnlLprPinjamMouseClicked(evt);
            }
        });

        IconDashboard8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Peminjaman");

        javax.swing.GroupLayout BpnlLprPinjamLayout = new javax.swing.GroupLayout(BpnlLprPinjam);
        BpnlLprPinjam.setLayout(BpnlLprPinjamLayout);
        BpnlLprPinjamLayout.setHorizontalGroup(
            BpnlLprPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlLprPinjamLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard8)
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlLprPinjamLayout.setVerticalGroup(
            BpnlLprPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlLprPinjamLayout.createSequentialGroup()
                .addGroup(BpnlLprPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlLprPinjamLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard8))
                    .addGroup(BpnlLprPinjamLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addGap(10, 10, 10))
        );

        BpnlLprPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BpnlLprPengembalianMouseClicked(evt);
            }
        });

        IconDashboard9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconDashboard.png"))); // NOI18N
        IconDashboard9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconDashboard9MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Pengembalian");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BpnlLprPengembalianLayout = new javax.swing.GroupLayout(BpnlLprPengembalian);
        BpnlLprPengembalian.setLayout(BpnlLprPengembalianLayout);
        BpnlLprPengembalianLayout.setHorizontalGroup(
            BpnlLprPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlLprPengembalianLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IconDashboard9)
                .addGap(28, 28, 28)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpnlLprPengembalianLayout.setVerticalGroup(
            BpnlLprPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpnlLprPengembalianLayout.createSequentialGroup()
                .addGroup(BpnlLprPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpnlLprPengembalianLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IconDashboard9))
                    .addGroup(BpnlLprPengembalianLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout pKiriLayout = new javax.swing.GroupLayout(pKiri);
        pKiri.setLayout(pKiriLayout);
        pKiriLayout.setHorizontalGroup(
            pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKiriLayout.createSequentialGroup()
                .addGroup(pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKiriLayout.createSequentialGroup()
                        .addGroup(pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pKiriLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(pKiriLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pKiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BpnlDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BpnlAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BpnlBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BpnlKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BpnlPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BpnlPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BpnlPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BpnlPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BpnlLprPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pKiriLayout.createSequentialGroup()
                                .addGroup(pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(BpnlLprPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pKiriLayout.setVerticalGroup(
            pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKiriLayout.createSequentialGroup()
                .addGroup(pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKiriLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pKiriLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)))
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlLprPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BpnlLprPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        getContentPane().add(pKiri, java.awt.BorderLayout.LINE_START);

        pKanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1439, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pKanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pDasar.setBackground(new java.awt.Color(204, 204, 204));

        pUtama.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1415, Short.MAX_VALUE)
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pDasarLayout = new javax.swing.GroupLayout(pDasar);
        pDasar.setLayout(pDasarLayout);
        pDasarLayout.setHorizontalGroup(
            pDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDasarLayout.setVerticalGroup(
            pDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pKanan.add(pDasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pKanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BpnlDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpnlDashboardMouseClicked
       menuDashboard dashboard = new menuDashboard();
       showPanel(dashboard);
    }//GEN-LAST:event_BpnlDashboardMouseClicked

    private void BpnlAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpnlAnggotaMouseClicked
        menuAnggota anggota = new menuAnggota();
        showPanel(anggota);
    }//GEN-LAST:event_BpnlAnggotaMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        new MenuPengembalian().setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void IconDashboard9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconDashboard9MouseClicked
        // TODO add your handling code here:
         new MenuPengembalian().setVisible(true);
    }//GEN-LAST:event_IconDashboard9MouseClicked

    private void BpnlLprPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpnlLprPinjamMouseClicked
        // TODO add your handling code here:
         new MenuPengembalian().setVisible(true);
    }//GEN-LAST:event_BpnlLprPinjamMouseClicked

    private void BpnlLprPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpnlLprPengembalianMouseClicked
        // TODO add your handling code here:
        new MenuPengembalian().setVisible(true);
    }//GEN-LAST:event_BpnlLprPengembalianMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BpnlAnggota;
    private javax.swing.JPanel BpnlBuku;
    private javax.swing.JPanel BpnlDashboard;
    private javax.swing.JPanel BpnlKategori;
    private javax.swing.JPanel BpnlLprPengembalian;
    private javax.swing.JPanel BpnlLprPinjam;
    private javax.swing.JPanel BpnlPeminjaman;
    private javax.swing.JPanel BpnlPenerbit;
    private javax.swing.JPanel BpnlPengembalian;
    private javax.swing.JPanel BpnlPetugas;
    private javax.swing.JLabel IconBuku;
    private javax.swing.JLabel IconDashboard;
    private javax.swing.JLabel IconDashboard1;
    private javax.swing.JLabel IconDashboard2;
    private javax.swing.JLabel IconDashboard3;
    private javax.swing.JLabel IconDashboard4;
    private javax.swing.JLabel IconDashboard5;
    private javax.swing.JLabel IconDashboard6;
    private javax.swing.JLabel IconDashboard7;
    private javax.swing.JLabel IconDashboard8;
    private javax.swing.JLabel IconDashboard9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pDasar;
    private javax.swing.JPanel pKanan;
    private javax.swing.JPanel pKiri;
    private javax.swing.JPanel pUtama;
    // End of variables declaration//GEN-END:variables
}
