

package Tampilan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.koneksi;
import View.menuCRUDPeminjaman;
/**
 *
 * @author rafli
 */
public class PopupDataAnggota extends javax.swing.JFrame {
    private Connection Conn = koneksi.getKoneksi();
    private DefaultTableModel tabmode;
    
    public menuCRUDPeminjaman agt;
    

    /**
     * Creates new form PopupAnggota
     */
    public PopupDataAnggota() {
        initComponents();
        datatable();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    protected void datatable() {
        // Struktur kolom tabel data anggota
        Object[] Baris = {"NIS", "NAMA ANGGOTA", "JENIS KELAMIN", "TELEPON","EMAIL"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelDataAnggota.setModel(tabmode);
        
        String sql = "SELECT * FROM data_anggota"; 
        try {
            Statement stat = Conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("nis"); 
                String b = hasil.getString("nama");
                String c = hasil.getString("jenis_kelamin");
                String d = hasil.getString("no_hp");
                String e = hasil.getString("email");
                
                String[] data = {a, b, c, d, e};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data awal: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataAnggota = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCariAnggota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelDataAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDataAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataAnggota);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Anggota");

        txtCariAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCariAnggotaMouseClicked(evt);
            }
        });
        txtCariAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariAnggotaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtCariAnggota))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCariAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariAnggotaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariAnggotaMouseClicked

    private void txtCariAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariAnggotaKeyPressed
    Object[] Baris = {"NIS", "NAMA ANGGOTA", "JENIS KELAMIN", "TELEPON", "EMAIL"};
        tabmode = new DefaultTableModel(null, Baris);
        
        String sql = "SELECT * FROM data_anggota WHERE nama LIKE '%" + txtCariAnggota.getText() 
                   + "%' OR nis LIKE '%" + txtCariAnggota.getText() + "%'";
        try {
            Statement stat = Conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("nis");
                String b = hasil.getString("nama");
                String c = hasil.getString("jenis_kelamin");
                String d = hasil.getString("no_hp");
                String e = hasil.getString("email");

                String[] data = {a, b, c, d, e};
                tabmode.addRow(data);
            }
            tabelDataAnggota.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat pencarian: " + e.getMessage());
        }
    }//GEN-LAST:event_txtCariAnggotaKeyPressed

    private void tabelDataAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataAnggotaMouseClicked
    int bar = tabelDataAnggota.getSelectedRow();
    
    // 1. Ambil data dari kolom tabel sesuai indeksnya
    String nis_terpilih = tabelDataAnggota.getValueAt(bar, 0).toString();  // Kolom NIS
    String nama_terpilih = tabelDataAnggota.getValueAt(bar, 1).toString(); // Kolom NAMA ANGGOTA
    // Kolom indeks 2 adalah JENIS KELAMIN (tidak kita kirim)
    String telp_terpilih = tabelDataAnggota.getValueAt(bar, 3).toString(); // Kolom TELEPON (Indeks 3)
    String email_terpilih = tabelDataAnggota.getValueAt(bar, 4).toString(); // Kolom EMAIL (Indeks 4)

    // 2. Kirimkan data ke variabel global yang ada di menuCRUDPeminjaman
    agt.nis = nis_terpilih;
    agt.nama_anggota = nama_terpilih;
    agt.telp_anggota = telp_terpilih;   // Ini yang tadi terlewat
    agt.email_anggota = email_terpilih; // Ini yang tadi terlewat
    
    // 3. Panggil method di menuCRUDPeminjaman untuk set teks ke field
    agt.itemTerpilihAnggota();
    
    // 4. Tutup popup data anggota
    this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_tabelDataAnggotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupDataAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataAnggota;
    private javax.swing.JTextField txtCariAnggota;
    // End of variables declaration//GEN-END:variables
}
